baseURL = 'https://kodu.ut.ee/~karl-mih'
languageCode = 'et-ee'
title = 'Arvuti riistvara ja arhitektuur'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
