name = 'ARA_Veebileht'
description = 'Theme description'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/inugami-dev64/ARA_Veebileht'

# If you have a running demo of the theme
demosite = 'https://kodu.ut.ee/~karl-mih'

tags = ['Riistvara', 'Arhitektuur']
features = []

# If the theme has multiple authors
authors = [
  {name = 'Karl-Mihkel Ott', homepage = 'https://karlott.net'},
  {name = 'Richard Leover', homepage = 'https://github.com/richardleoverr'}
]

# If porting an existing theme
[original]
  author = 'Name of original author'
  homepage = 'Website of original author'
  repo = 'https://github.com/owner/repo'
