baseURL = 'https://kodu.ut.ee/~karl-mih'
languageCode = 'et-ee'
title = 'Arvuti riistvara ja arhitektuur (LOFY.03.079)'
theme = 'ARA_Veebileht'
defaultContentLanguage = 'et'
defaultContentLanguageInSubdir = true
summaryLength = 30

[taxonomies]
    tag = 'teemad'